package model;
// Generated Mar 5, 2019 12:39:11 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Factura generated by hbm2java
 */
public class Factura  implements java.io.Serializable {


     private Integer idFactura;
     private Cliente cliente;
     private Usuario usuario;
     private Vehiculo vehiculo;
     private Date fechaFactura;
     private int valorFactura;

    public Factura() {
    }

    public Factura(Cliente cliente, Usuario usuario, Vehiculo vehiculo, Date fechaFactura, int valorFactura) {
       this.cliente = cliente;
       this.usuario = usuario;
       this.vehiculo = vehiculo;
       this.fechaFactura = fechaFactura;
       this.valorFactura = valorFactura;
    }
   
    public Integer getIdFactura() {
        return this.idFactura;
    }
    
    public void setIdFactura(Integer idFactura) {
        this.idFactura = idFactura;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Vehiculo getVehiculo() {
        return this.vehiculo;
    }
    
    public void setVehiculo(Vehiculo vehiculo) {
        this.vehiculo = vehiculo;
    }
    public Date getFechaFactura() {
        return this.fechaFactura;
    }
    
    public void setFechaFactura(Date fechaFactura) {
        this.fechaFactura = fechaFactura;
    }
    public int getValorFactura() {
        return this.valorFactura;
    }
    
    public void setValorFactura(int valorFactura) {
        this.valorFactura = valorFactura;
    }




}


