package model;
// Generated Mar 5, 2019 12:39:11 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoUsuario generated by hbm2java
 */
public class TipoUsuario  implements java.io.Serializable {


     private Integer idTipoUsuario;
     private String nombreTipoUsuario;
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);

    public TipoUsuario() {
    }

	
    public TipoUsuario(String nombreTipoUsuario) {
        this.nombreTipoUsuario = nombreTipoUsuario;
    }
    public TipoUsuario(String nombreTipoUsuario, Set<Usuario> usuarios) {
       this.nombreTipoUsuario = nombreTipoUsuario;
       this.usuarios = usuarios;
    }
   
    public Integer getIdTipoUsuario() {
        return this.idTipoUsuario;
    }
    
    public void setIdTipoUsuario(Integer idTipoUsuario) {
        this.idTipoUsuario = idTipoUsuario;
    }
    public String getNombreTipoUsuario() {
        return this.nombreTipoUsuario;
    }
    
    public void setNombreTipoUsuario(String nombreTipoUsuario) {
        this.nombreTipoUsuario = nombreTipoUsuario;
    }
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }




}


