package model;
// Generated Mar 5, 2019 12:39:11 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Vehiculo generated by hbm2java
 */
public class Vehiculo  implements java.io.Serializable {


     private Integer idVehiculo;
     private String placaVehiculo;
     private int modeloVehiculo;
     private int precioVehiculo;
     private Set<Factura> facturas = new HashSet<Factura>(0);

    public Vehiculo() {
    }

	
    public Vehiculo(String placaVehiculo, int modeloVehiculo, int precioVehiculo) {
        this.placaVehiculo = placaVehiculo;
        this.modeloVehiculo = modeloVehiculo;
        this.precioVehiculo = precioVehiculo;
    }
    public Vehiculo(String placaVehiculo, int modeloVehiculo, int precioVehiculo, Set<Factura> facturas) {
       this.placaVehiculo = placaVehiculo;
       this.modeloVehiculo = modeloVehiculo;
       this.precioVehiculo = precioVehiculo;
       this.facturas = facturas;
    }
   
    public Integer getIdVehiculo() {
        return this.idVehiculo;
    }
    
    public void setIdVehiculo(Integer idVehiculo) {
        this.idVehiculo = idVehiculo;
    }
    public String getPlacaVehiculo() {
        return this.placaVehiculo;
    }
    
    public void setPlacaVehiculo(String placaVehiculo) {
        this.placaVehiculo = placaVehiculo;
    }
    public int getModeloVehiculo() {
        return this.modeloVehiculo;
    }
    
    public void setModeloVehiculo(int modeloVehiculo) {
        this.modeloVehiculo = modeloVehiculo;
    }
    public int getPrecioVehiculo() {
        return this.precioVehiculo;
    }
    
    public void setPrecioVehiculo(int precioVehiculo) {
        this.precioVehiculo = precioVehiculo;
    }
    public Set<Factura> getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Set<Factura> facturas) {
        this.facturas = facturas;
    }




}


